cmake_minimum_required(VERSION 3.14)

file(REMOVE "${REPORT}")
execute_process(COMMAND ${TEST_COMMAND}
                RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
message("${stdout}${stderr}")

if (EXPECT_EXIT STREQUAL "nonzero")
    if (NOT "${result}" MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "Expected an error exit, got ${result}")
    endif ()
elseif (NOT "${result}" STREQUAL "${EXPECT_EXIT}")
    message(FATAL_ERROR "Exit status ${result}; expected ${EXPECT_EXIT}")
endif ()

set(OUTPUT "${stdout}${stderr}")
if (EXPECT_REPORT)
    file(READ "${REPORT}" REPORT)
endif ()
foreach(stream IN ITEMS OUTPUT REPORT)
    foreach(expected IN LISTS EXPECT_${stream})
        string(FIND "${${stream}}" "${expected}" position)
        if (position EQUAL -1)
            message(FATAL_ERROR "Missing '${expected}' in ${stream}:\n${${stream}}")
        endif ()
    endforeach()
endforeach()
if (FORBID_PASSED AND OUTPUT MATCHES "This test is considered PASSED")
    message(FATAL_ERROR "Unchecked solution was reported as passed")
endif ()
